import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  modal: {
    justifyContent: 'center',
  },
  m1screen: {
    backgroundColor: '#3b3b3b',
    width: 350,
    height: 400,
    marginTop: 150,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#a9a9a9',
  },
  m1inputarea: {
    backgroundColor: '#4E4D4D',
    width: '80%',
    marginBottom: 20,
    borderRadius: 10,
  },
  m1button: {
    backgroundColor: '#4E4D4D',
    width: 100,
    height: 50,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  m1close: {
    width: 30,
    height: 30,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#4e4d4d',
    marginBottom: 30,
    marginRight: 30,
    borderRadius: 50,
  },
  header: {
    backgroundColor: '#373636',
    width: 250,
    borderBottomEndRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: 50,
    height: 50,
    margin: 5,
  },
  title: {
    fontSize: 24,
    color: '#fff',
    marginLeft: 30,
  },
  plus: {
    backgroundColor: '#4E4D4D',
    width: 50,
    height: 50,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    marginBottom: 50,
    right: 20,
  },
  plust: {
    fontSize: 26,
    color: '#A9A9A9',
  },
  edit: {
    width: 20,
    height: 20,
    tintColor: '#a9a9a9',
  },
  editbutton: {
    width: 30,
    height: 30,
    borderRadius: 20,
    backgroundColor: '#4e4d4d',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    marginTop: 5,
  },
  list: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#373636',
    marginTop: 10,
    width: '80%',
    borderRadius: 20,
    padding: 10,
  },
  listtitle: {
    color: '#a9a9a9',
    fontSize: 20,
    fontWeight: 'bold',
    width: 200,
  },
  two: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
  },
  m1inputarea2: {
    backgroundColor: '#4E4D4D',
    width: 130,
    marginBottom: 20,
    borderRadius: 10,
  },
});
