import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  modal: {
    justifyContent: 'center',
  },
  m1screen: {
    backgroundColor: '#3b3b3b',
    width: 350,
    height: 250,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  m1inputarea: {
    backgroundColor: '#4E4D4D',
    width: '80%',
    marginBottom: 20,
    borderRadius: 10,
  },
  m1button: {
    backgroundColor: '#4E4D4D',
    width: 100,
    height: 50,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  m1close: {
    width: 30,
    height: 30,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#4e4d4d',
    marginBottom: 30,
    marginRight: 30,
    borderRadius: 50,
  },
  m2screen: {
    backgroundColor: '#3b3b3b',
    width: 350,
    height: 250,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },

  m2button: {
    backgroundColor: '#4E4D4D',
    width: 100,
    height: 50,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  m2close: {
    width: 30,
    height: 30,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#4e4d4d',
    marginBottom: 30,
    marginRight: 30,
    borderRadius: 50,
  },
  m2item: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '50%',
  },
  count: {
    backgroundColor: '#4e4d4d',
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  m2jumlah: {
    fontSize: 20,
    color: '#A9A9A9',
  },
  m3screen: {
    backgroundColor: '#3b3b3b',
    width: 350,
    height: 250,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  m3inputarea: {
    backgroundColor: '#4E4D4D',
    width: '80%',
    marginBottom: 20,
    borderRadius: 10,
  },
  m3button: {
    backgroundColor: '#4E4D4D',
    width: 100,
    height: 50,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  m3close: {
    width: 30,
    height: 30,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#4e4d4d',
    marginBottom: 30,
    marginRight: 30,
    borderRadius: 50,
  },
  tabelbarang: {
    width: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2,
  },
  tabelhj: {
    width: 75,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2,
  },
  tabeljumlah: {
    width: 55,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2,
  },
  tabelharga: {
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2,
  },
  edit: {
    width: 20,
    height: 20,
  },
  editbutton: {
    width: 30,
    height: 30,
    borderRadius: 20,
    backgroundColor: '#3b3b',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    marginTop: 5,
  },
  uang: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputuang: {
    width: '49%',
    borderWidth: 2,
    borderRightWidth: 0,
    height: 55,
  },
  total: {
    width: '49%',
    borderWidth: 2,
    height: 55,
    justifyContent: 'center',
  },
  pembayaran: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  pay: {
    width: 100,
    height: 50,
    backgroundColor: '#4E4D4D',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
  },
  payt: {
    color: '#a9a9a9',
    fontWeight: 'bold',
  },
  plus: {
    backgroundColor: '#4E4D4D',
    width: 50,
    height: 50,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    marginBottom: 150,
    right: 20,
  },
  plust: {
    fontSize: 26,
    color: '#A9A9A9',
  },
  barangTitle: {
    color: '#a9a9a9',
    fontWeight: 'bold',
    fontSize: 24,
    marginBottom: 50,
  },
  barang: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
  },
  barangItem: {
    color: '#a9a9a9',
    fontWeight: 'bold',
    fontSize: 16,
  },
  barangscreen: {
    backgroundColor: '#3b3b3b',
    marginTop: 25,
    width: 350,
    maxWidth: 350,
    maxHeight: 600,
    height: 600,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  harga: {
    color: '#a9a9a9',
    fontWeight: 'bold',
    fontSize: 16,
    marginTop: 50,
    marginBottom: 10,
  },
  harga2: {
    color: '#a9a9a9',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 10,
  },

  harga3: {
    color: '#a9a9a9',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 50,
  },
});
